FROM node:12 as build

WORKDIR /code/frontend

# add `/app/node_modules/.bin` to $PATH
ENV PATH /code/frontend/node_modules/.bin:$PATH

COPY package.json ./
COPY package-lock.json ./

RUN npm ci --silent
RUN npm install --silent
COPY . ./
RUN npm run build

FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY --from=build /code/frontend/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d

EXPOSE 3000

CMD ["nginx", "-g", "daemon off;"]
