version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend:
    build: ./backend
    command: >
      bash -c "python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8080"
    volumes:
      - ./backend:/code/backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    links:
      - db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    # volumes:
    #   - ./frontend:/code/frontend
    #   - ./frontend/src:/code/frontend/src
    #   - /code/frontend/node_modules
    ports:
      - "3000:3000"
    # environment:
    #   - NODE_ENV=development
    # command: npm start
    depends_on:
      - backend
    # stdin_open: true
    # tty: true
