# Generated by Django 2.2.15 on 2020-08-09 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_auto_20200807_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='groupExpense',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='expense.Expense'),
        ),
    ]
