# Generated by Django 2.2.15 on 2020-08-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_auto_20200807_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='notes',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
