# Generated by Django 2.2.15 on 2020-08-10 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_auto_20200809_1119'),
        ('expense', '0003_paymenthistory_groupexpense'),
    ]

    operations = [
    ]
