# Generated by Django 2.2.15 on 2020-08-10 01:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_merge_20200809_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousPaymentLink',
            fields=[
                ('link', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.Expense')),
            ],
            options={
                'unique_together': {('expense', 'link')},
            },
        ),
    ]
