# Generated by Django 2.2.15 on 2020-08-10 02:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0005_anonymouspaymentlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='anon_link',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.DeleteModel(
            name='AnonymousPaymentLink',
        ),
    ]
